[package]
name = "windows_rs_d3d11"
version = "0.1.0"
authors = ["LNSEAB <691752+LNSEAB@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bindings = { path = "bindings" }
wita = "0.7.0"
anyhow = "1.0.38"
windows = { git = "https://github.com/microsoft/windows-rs" }
